name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests (可选，若有测试)
      run: |
        if [ -f build/test ]; then
          ./build/test
        fi
